In [14]:
# Import packages
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsOneClassifier
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from collections import Counter
from parse import preprocess

In [15]:
# Function to show classification report for Cross Validation
def classification_report_with_accuracy_score(y_true, y_pred):
    print(classification_report(y_true, y_pred)) # print classification report
    return accuracy_score(y_true, y_pred) # return accuracy score

In [16]:
# Pre-parse the dataset
data = preprocess("rawfile_blood.csv")

robust          368
prefrail_mci    268
prefrail        250
mci             142
frail_mci        86
frail             9
Name: condition, dtype: int64

####################################################################
Number of Rows of Dataframe:
1123
Number of Columns of Dataframe:
59

####################################################################
Threshold for number of NULLs in a column: 0.1095
Number of Columns before Parsing for Too Many NULLs in a column:
59
Number of Columns after Parsing for Too Many NULLs in a column:
51

Columns Removed:
B1_b5
B4_a1
B4_a3
B4_a4
B4_a6
B4_b1
B4_b3
B5_a1

####################################################################
Number of Columns after dropping A1_2, B1_b4, B2_c3, B4_b2 for inconsistent data types:
47

####################################################################
Number of Rows before Parsing NULLs in data:
1123
Number of Rows after Parsing NULLs in data:
1015


In [17]:
# Initialise counters for each condition
frail = 0
frail_mci = 0
mci = 0
prefrail_mci = 0
prefrail = 0
robust = 0

# Count rows of data for each condition
for i in range(0, len(data)):
	if data.at[i, 'condition'] == 'frail':
		frail += 1
	elif data.at[i, 'condition'] == 'frail_mci':
		frail_mci += 1
	elif data.at[i, 'condition'] == 'mci':
		mci += 1
	elif data.at[i, 'condition'] == 'prefrail_mci':
		prefrail_mci += 1
	elif data.at[i, 'condition'] == 'prefrail':
		prefrail += 1
	elif data.at[i, 'condition'] == 'robust':
		robust += 1
        
# Display number of rows (frequency) for each condition (label)
print("\n####################################################################")
print("Labels with frequencies:")
print("Frail:", frail)
print("Frail + MCI:", frail_mci)
print("MCI:", mci)
print("Prefrail + MCI:", prefrail_mci)
print("Prefrail:", prefrail)
print("Robust:", robust)


####################################################################
Labels with frequencies:
Frail: 7
Frail + MCI: 76
MCI: 133
Prefrail + MCI: 233
Prefrail: 223
Robust: 343


In [18]:
c = data['condition'].value_counts()
condition = c.index
c

robust          343
prefrail_mci    233
prefrail        223
mci             133
frail_mci        76
frail             7
Name: condition, dtype: int64

In [19]:
for i in range(len(condition)):
    data['condition'].replace(condition[i], i, inplace = True)

data.head()

mtag  condition  A1_1  A2_1  A3_1  B1_a  B1_a1  B1_a2  B1_a3  B1_a4  \
0  ME02646          5   196    24  46.5   121   3.93   0.37     95     31   
1  ME03109          5   200    23  55.6   142   4.82   0.42     87     30   
2  ME06997          5   441    20  76.8   105   4.54   0.41     90     30   
3  ME07149          5   265    16  47.2   122   4.53   0.39     86     27   
4  ME07700          5   425    14  31.3   124   4.44   0.38     85     28   

   ...  B2_d6  B2_d7  B2_d8  B2_d9   B3  B4_a2  B4_a5  B5_a2  B5_a3   B6  
0  ...      7     12     13      6  0.2    6.0  1.011   1.14    4.1  5.9  
1  ...      7     20     17     26  3.1    5.0  1.011   3.25    4.6  8.5  
2  ...      5     16     19     15  1.4    7.0  1.023   2.14    4.0  6.4  
3  ...      8     24     19     21  2.1    5.5  1.012   1.06    4.7  6.1  
4  ...      6     20     23     23  6.0    5.5  1.013   1.95    3.8  5.8  

[5 rows x 47 columns]

In [20]:
data.tail()

mtag  condition  A1_1  A2_1  A3_1  B1_a  B1_a1  B1_a2  B1_a3  B1_a4  \
1010  MV00454          0   220    19  67.5   138   4.66   0.42     91     30   
1011  MV00456          0   334    18  51.0   139   4.63   0.42     91     30   
1012  MV00460          0   418    17  61.0   122   4.18   0.38     90     29   
1013  MV00502          0   393    18  43.1   136   4.57   0.43     94     30   
1014  MV00510          0   371    24  55.9   127   4.41   0.40     90     29   

      ...  B2_d6  B2_d7  B2_d8  B2_d9   B3  B4_a2  B4_a5  B5_a2  B5_a3   B6  
1010  ...     20     10     17      8  6.6    7.0  1.015   1.29    4.5  6.2  
1011  ...     16     22     35     40  1.0    6.0  1.015   1.88    3.9  5.6  
1012  ...     19     20     23     15  0.4    6.5  1.005   3.58    4.0  5.6  
1013  ...     13     11     22     23  0.7    7.0  1.009   0.92    4.1  6.0  
1014  ...     13     14     16     12  7.5    8.0  1.017   2.45    4.5  6.2  

[5 rows x 47 columns]

In [21]:
y = data['condition']

features = ['A1_1', 'A2_1', 'A3_1', 'B1_a', 'B1_a1', 'B1_a2',
       'B1_a3', 'B1_a4', 'B1_a5', 'B1_a6', 'B1_b', 'B1_b1', 'B1_b2', 'B1_b3',
       'B1_c', 'B1_d', 'B2_a1', 'B2_a2', 'B2_a3', 'B2_a4', 'B2_a5', 'B2_b1',
       'B2_b2', 'B2_b3', 'B2_c1', 'B2_c2', 'B2_c4', 'B2_c5', 'B2_c6', 'B2_c7',
       'B2_d1', 'B2_d2', 'B2_d3', 'B2_d4', 'B2_d5', 'B2_d6', 'B2_d7', 'B2_d8',
       'B2_d9', 'B3', 'B4_a2', 'B4_a5', 'B5_a2', 'B5_a3', 'B6']
X_old = data[features]

In [22]:
X = X_old
X = StandardScaler().fit_transform(X_old)
X = MinMaxScaler().fit_transform(X_old)

In [23]:
# Summarise the new class distribution
counter = Counter(y)
print(counter)

Counter({0: 343, 1: 233, 2: 223, 3: 133, 4: 76, 5: 7})


In [24]:
# Transform the dataset using SMOTE
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

counter = Counter(y)
print(counter)

Counter({5: 343, 4: 343, 3: 343, 1: 343, 2: 343, 0: 343})


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 1)

In [26]:
svm_model = OneVsOneClassifier(SVC(kernel='linear', gamma='auto'))
svm_model.fit(X_train, y_train)
print("Logistic Regression:", svm_model.score(X_test, y_test).round(3))

Logistic Regression: 0.425


In [27]:
# Calculating for Random Forest Classifier
svm_pred = svm_model.predict(X_test)

print('Performance Metrics for SVM:\n')
print(accuracy_score(y_test, svm_pred).round(5), '\n')
print(confusion_matrix(y_test, svm_pred), '\n')
print(classification_report(y_test, svm_pred))

Performance Metrics for SVM:

0.42476 

[[ 41   9  36  32  10  10]
 [ 18  22  26  36  28  11]
 [ 27  11  35  34  16  11]
 [ 26  11  14  56  16  16]
 [ 19  23  14  10  60  10]
 [  0   0   0   0   0 136]] 

              precision    recall  f1-score   support

           0       0.31      0.30      0.30       138
           1       0.29      0.16      0.20       141
           2       0.28      0.26      0.27       134
           3       0.33      0.40      0.36       139
           4       0.46      0.44      0.45       136
           5       0.70      1.00      0.82       136

    accuracy                           0.42       824
   macro avg       0.40      0.43      0.40       824
weighted avg       0.40      0.42      0.40       824

